// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewKlSEnUrPiC2luY1_e0WD9zgAVBetCE',
    appId: '1:434848050715:web:b92753eb8258dfdf6f52be',
    messagingSenderId: '434848050715',
    projectId: 'smart-farm-d7800',
    authDomain: 'smart-farm-d7800.firebaseapp.com',
    databaseURL: 'https://smart-farm-d7800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-farm-d7800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALq_1_FCMYpWiCuvVc5cjHFaSc0_pXMOc',
    appId: '1:434848050715:android:916f016740e64de26f52be',
    messagingSenderId: '434848050715',
    projectId: 'smart-farm-d7800',
    databaseURL: 'https://smart-farm-d7800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-farm-d7800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy8gI7oXDFn3lsY2WYVu1YiNrY1OyZ_RE',
    appId: '1:434848050715:ios:24062ad073a285ac6f52be',
    messagingSenderId: '434848050715',
    projectId: 'smart-farm-d7800',
    databaseURL: 'https://smart-farm-d7800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-farm-d7800.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy8gI7oXDFn3lsY2WYVu1YiNrY1OyZ_RE',
    appId: '1:434848050715:ios:24062ad073a285ac6f52be',
    messagingSenderId: '434848050715',
    projectId: 'smart-farm-d7800',
    databaseURL: 'https://smart-farm-d7800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-farm-d7800.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAewKlSEnUrPiC2luY1_e0WD9zgAVBetCE',
    appId: '1:434848050715:web:cb704c5611648e436f52be',
    messagingSenderId: '434848050715',
    projectId: 'smart-farm-d7800',
    authDomain: 'smart-farm-d7800.firebaseapp.com',
    databaseURL: 'https://smart-farm-d7800-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-farm-d7800.firebasestorage.app',
  );
}
